---
title: "Course Landing Page"
format: html
embed-resources: true 
---

Topics to be covered:

1. Unit1: Same as Current Structure (Use Chapter2: 2.1 - 2.2 and 2.4)
2. Unit2: Refresher on Linear Regression & Resampling methods (Use IMS 2e: CH7,8 | Use Chapters3, 5 ISLR)
3. Unit3: Tree based methods (Use Chapter8 ISLR)
4. Unit4: Same as Unit2 of the Current Structure
5. Unit5: Sentiment analysis

If we have more time we may also cover one or more of:

1. RDD
2. RCT
3. IV

**Lecture Slides**

1. [Lecture Slides](23-01-2026-intro-to-statistical-learning.html): Intro to Statistical 
Learning.
2. [Lecture Slides](26-01-2026-linear-regression-refresher.html): Intro to Modern Statistics
3. [Lecture Slides](28-01-2026-resampling-methods.html): Resampling
4. [Lecture Slides](12-02-2026-decision-trees-emsemble-methods.html): Decision Trees and Ensemble Methods

Assessment Details

Type        |   # ILO linkages  | Assessment Percentage |  Details                       
------------|-------------------|-----------------------|------------------------------------------------------
Quiz        | 1                 | 15                    | Intro to statistical learning and Linear Regression
inclass exam| 1                 | 30                    | LR, resampling, decision trees
inclass exam| 2                 | 30                    | PCA, sentiment analysis, Ethics of data
CP          | 3                 | 5                     | 
GRP Prjoect | 2                 | 20                    |  apply machine methods learned in class to real data and present their findings. 

May change with adequate notice.

Links to resourses:

1. [ISLR](https://www.statlearning.com/), also check out the youtube videos they have. Use the june 2023 corrected version of the book
2. [IMS](https://openintro-ims.netlify.app/)
3. For a simulated and intuitive explanation of Bias-Variance Trade off see [Link](https://mlu-explain.github.io/bias-variance/)